import Link from "next/link";
import { notFound } from "next/navigation";
import { getAppSession } from "@/lib/app-session";
import { formatWhen, readRun, type RunStep } from "@/lib/automations";
import { PlatformServerError } from "@/lib/platform-server";
import SectionCard from "@/components/dashboard/SectionCard";
import { StatusPill } from "@/components/dashboard/StatusPill";
import { Kicker } from "@/components/ui/Kicker";

/**
 * One run, step by step.
 *
 * The screen renders `steps` — what the automation reported against the steps
 * its manifest declares — and not `events`, which is the platform's own record
 * of state transitions. Both come back from the same read; only one is written
 * for a person.
 */

export const dynamic = "force-dynamic";

export default async function RunDetailPage(
  props: PageProps<"/account/runs/[runId]">,
) {
  // `PageProps` is generated by `next typegen`, which is what makes the route
  // literal above type-checked against the actual file tree: renaming the
  // segment breaks the build rather than producing an undefined param.
  const { runId } = await props.params;
  const session = await getAppSession();
  const workspaceId = session?.user.workspaceId ?? session?.workspaces[0]?.id;
  if (!workspaceId) notFound();

  let detail;
  try {
    detail = await readRun(workspaceId, runId);
  } catch (error) {
    // A run in another workspace answers 404, same as one that does not exist.
    // Rendering the same page for both is what keeps that true here.
    if (error instanceof PlatformServerError && error.status === 404)
      notFound();
    throw error;
  }

  const { run, steps } = detail;

  return (
    <SectionCard
      title="Run"
      subheader={`${run.templateId} · v${run.templateVersion}`}
      primaryAction={<StatusPill status={run.status} />}
    >
      <div className="py-5 first:pt-0">
        <dl className="grid gap-3 sm:grid-cols-3">
          <Fact
            label="Started"
            value={run.startedAt ? formatWhen(run.startedAt) : "—"}
          />
          <Fact
            label="Ended"
            value={run.endedAt ? formatWhen(run.endedAt) : "—"}
          />
          <Fact
            label="Trigger"
            value={
              run.origin === "approval-continuation"
                ? "After approval"
                : "Manual"
            }
          />
        </dl>

        {/* A continuation belongs to the run it continues. The link is how a
            person follows the chain rather than reading two unrelated runs. */}
        {run.continuesRunId ? (
          <p className="mt-4 text-sm text-[var(--muted)]">
            Continues{" "}
            <Link
              href={`/account/runs/${run.continuesRunId}`}
              className="text-[var(--accent)] underline underline-offset-2"
            >
              the run that was held
            </Link>
            .
          </p>
        ) : null}
      </div>

      <div className="py-5">
        <h2 className="text-xs font-medium tracking-wide text-[var(--muted)] uppercase">
          Steps
        </h2>
        {steps.length === 0 ? (
          <p className="mt-3 text-sm text-[var(--muted)]">
            No steps reported yet.
          </p>
        ) : (
          <ol className="mt-4 flex flex-col gap-4">
            {steps.map((step) => (
              <StepRow key={step.id} step={step} />
            ))}
          </ol>
        )}
      </div>
    </SectionCard>
  );
}

function StepRow({ step }: { step: RunStep }) {
  return (
    <li className="flex flex-col gap-1 border-l-2 border-[var(--ring)] pl-4">
      <div className="flex flex-wrap items-center gap-2">
        {/* The manifest's own kicker vocabulary. Kicker is the component the
            design system already uses for exactly this eyebrow. */}
        <Kicker className="mb-0">{step.stepId}</Kicker>
        <StatusPill status={outcomeStatus(step.outcome)} />
      </div>
      <p className="text-sm text-[var(--text)]">{step.summary}</p>
      {step.heldReason ? (
        <p className="text-xs text-[var(--warning-text)]">{step.heldReason}</p>
      ) : null}
      <p className="text-xs text-[var(--muted)]">
        {formatWhen(step.occurredAt)}
      </p>
    </li>
  );
}

/**
 * A step outcome in the vocabulary StatusPill already knows.
 *
 * `ok` is the one word the pill has no tone for, because no status anywhere else
 * uses it. Mapping it to `succeeded` reuses the map instead of growing it.
 */
function outcomeStatus(outcome: RunStep["outcome"]): string {
  return outcome === "ok" ? "succeeded" : outcome;
}

function Fact({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <dt className="text-xs text-[var(--muted)]">{label}</dt>
      <dd className="mt-0.5 text-sm text-[var(--text)]">{value}</dd>
    </div>
  );
}
